version: "3.5"

networks:
  company-network:
    driver: bridge
services:
  company-app:
    build:
      context: "./.docker/php"
      args:
        domain: ${APP_DOMAIN:-companysub}
    container_name: company-app
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - ./company-checkout:/var/www/html/company-checkout
      - ./atendimento-wpp:/var/www/html/atendimento-wpp
      - ./wppconnect-server:/var/www/html/wppconnect-server
      - ./.docker/xdebug/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - 80:80
      - 443:443
      - 21465:21465
      - 9002:9003
    networks:
      - company-network
  company-db:
    image: mysql:5.7.40-debian
    container_name: company-db
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-company}
      - MYSQL_DATABASE=${DB_DATABASE:-company_db}
      - MYSQL_USER=${DB_USERNAME:-company}
      - MYSQL_PASSWORD=${DB_PASSWORD:-company}
      - TZ=America/Sao_Paulo
    networks:
      - company-network
volumes:
  db-volume:
